---
title       : Loan Payment Calculator Slides
subtitle    : Use of Loan Payment Calculator Web Application
author      : Peter Whitney
job         : Aspiring Data Scientist
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [quiz]     # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

--- 

## Description
#### The Loan Payment Calculator is a simple web based
#### application designed to accept simple loan terms 
#### as inout and quickly calculate the monthly payment
#### for the given loan terms.

--- .class #id

## Input Variables
 
#### The user specifies the following input variables
 
1. Loan Amount
2. Interest Rate
3. Term in years
 
#### Then presses the "Calculate" button

--- .class #id

## Results
 
#### The application quickly calculates the monthly
#### loan payment for in the input loan terms and
#### renders the monthly payment as a result.
  
#### A link to a github repository is also provided
#### to support inspecting the very extensive source
#### code for this application.

--- &radio

## Survey

Did you find the Loan Payment Calculator useful?
 
1. _Yes_
2. No

*** .hint 

Yes

*** .explanation 

Well I tried to make it useful
